#!usr/bin/bash

#CREATE DIRECTORY FOR ALL GENERATED RESULTS
mkdir -p B132026_results

#PATH TO PAIRED END FASTQ SEQUENCES (CHANGE AS REQUIRED)
SEQPATH=/localdisk/data/BPSM/ICA1/fastq/

#PATH TO REFERENCE GENOME (CHANGE AS REQUIRED)
REFPATH=/localdisk/data/BPSM/ICA1/Tcongo_genome/

#GENERATE FASTQC REPORTS
fastqc ${SEQPATH}/*.fq.gz -o ./B132026_results/ 
